### ISSUE TITLE
.mov files not supported

### ISSUE THREAD

**Issue by hilgart** [KenT2/pipresents#17]
omxplayer has no problem playing .mov files. When you try to add a .mov track you get a "file extension not recognized." It's a common video format actually. Any chance we can get a fix? I just downloaded the latest (v 1.1.2b according to the changelog) yesterday.

**Comment by KenT2** [comment]
If you edit the file pp_editor.py using Idle (2.7) or leafpad than on line 32 you can add additional video types.

Alternatively when running the Pi Presents editor add a new video track and then use the file chooser to select the video. IIRC this bypasses the acceptable format check.

**Comment by hilgart** [comment]
True. That worked just fine.
