### ISSUE TITLE
Image files not being downscaled

### ISSUE THREAD

**Issue by hilgart** [KenT2/pipresents#18]
I am getting inconsistent behaviour with my JPEG images, most of which are larger than the screen resolution. On a few occasions pipresents has correctly downscaled them to fit the fullscreen resolution. Mostly however it doesn't and just a portion of the image displays. I could write my own downscaler but I'd rather not have to do that. It looks like pipresents was designed to do this.

**Comment by KenT2** [comment]
[pipresents] does not scale images. You need to move to [pipresents-next].

[pipresents-next] will very soon become the stable starter's version as I shall not be developing it anymore; only bug fixes. I have nearly finished gaples which will become the beta.

 You will need to add in .mov, In this version It is in pp_definitions.py
