### ISSUE TITLE
Make Pi Presents Occupy the Whole Screen

### ISSUE THREAD

**Issue by bvandenberg** [KenT2/pipresents#19]
I have a problem with this. I exactly followed the steps in section 5.6 of the manual. But the file /home/pi/.config/openbox/lxde-rc.xml is not present yet on my installation. I don't even have a openbox folder in my .config directory.

I tried adding a new lxde-rc.xml with the content below but that didn't work.

Do you have a clue how to fix this?
Thx.

```
<applications>
<application name="fspipresents">
<decor>no</decor>
</application>
</applications>

**Comment by KenT2** [comment]
Are you using a version of Raspbian on or post 24/12/2014. I suspect the user interface changes that  were made in that version has removed or moved this part of the directory structure. I am still pre that version so cannot search for it.

[pipresents-next] implements fullscreen in a different way (in pipresents.py) which would be my  solution however I suggest you move to [pipresents-next] as I am going to stop supporting [pipresents] in the near future.

Anybody found this problem?

**Comment by bvandenberg** [comment]
I have updated to [pipresents-next]. Fullscreen works great! I probably used a quite recent version of Raspian indeed. 
Thx for the great software BTW!
