### ISSUE TITLE
Mouse Support?

### ISSUE THREAD

**Issue by aaronjeline** [KenT2/pipresents#21]
is it possible to have both mouse support and have the slides move forward automatically. I the default "auto" progress behaviour but with the mouse as opposed the the arrow keys.

Any ideas?

**Comment by KenT2** [comment]
Use 'click areas' In [pipresents-gapless] these can be used in mediashows. Click areas will use only the left mouse button so you must click on a certain area of the screen. Click areas  can be transparent if necessary.
