### ISSUE TITLE
Gpio + But

### ISSUE THREAD

**Issue by Vanderghen** [KenT2/pipresents#22]
Where are the button (but) definitions located? e.g. but1, 2, 3, 4 in radiobuttonshow refer to what gpio pins. I notice there is a file  pp_buttons.py at GitHub but there is no such file in my download. Does this have anything to do with the button definitions? And where are pp-key-1 etc defined?

**Comment by KenT2** [comment]
I suspect you are reading the manual for [pipresents-next] and the code for [pipresents]. [pipresents] is unsupported and will probably not work on Raspbian Jessie. Please upgrade.

**Comment by Vanderghen** [comment]
Ken:

 

No, I downloaded pp-next, the whole package, though as the instructions say,
I renamed the folder to pipresents. The program works fine on Jessie. 

 

But what I am wondering about is how the 4 button inputs in radiobutton show
are defined and made to cause some actions. They are gpio, but which ones?
And how are they defined in the program, i.e. how can I assign an action to
but1, and another one to but2, etc. Where is this done?

 

Chris Sia

 

  _____

**Comment by KenT2** [comment]
I undersand now, I was confused by you posting in the [pipresents] repository

The file gpio.cfg in the profile associates GPIO pins with symbolic names. The links field of the show associates the symbbolic name with the command (play)

For keys the file keys.cfg does the same for special keys. However for alphanumeric keys the association is automatic e.g. key a associates to the symbolic name pp-kkey-a
