### ISSUE TITLE
omx run-time commands not working in gapless ver 1.3

### ISSUE THREAD

**Issue by rongerhards** [KenT2/pipresents#24]
I was successfully able to trigger next and previous chapters in the "next" version.  The bindings in controls.cfg allowed me to assign 
nextchapter = omx-i 
prevchapter = omx-o

In the gapless version 1.3, I placed the runtime controls in the controls tab in the track (I also tried using the controls tab in the show).
nextchapter omx-i
prevchapter omx-o
but this does not work.

the pause control does work however.
Skipping chapters is important as it allows me to run a video, and jump back to the 1st chapter before the "action" part of the video begins.  When triggered, it would jump forward to the 2nd chapter to the action part of the video.

**Comment by KenT2** [comment]
moved to PIpresents gapless issue #49
